version: '3.9'

services:
  user-service:
    build:
      context: ./user_service
    container_name: user-service
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "8001:8001"
    networks:
      - app-network
    depends_on:
      - user-db

  wishlist-gift-service:
    build:
      context: ./wishlist_gift_service
    container_name: wishlist-gift-service
    environment:
      - POSTGRES_DB=wishlist_db
      - POSTGRES_USER=wishlist
      - POSTGRES_PASSWORD=password
      - USER_SERVICE_URL=http://user-service:8001
    ports:
      - "8002:8002"
    networks:
      - app-network
    depends_on:
      - wishlist-db
      - user-service

  user-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=user_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - app-network
    ports:
      - "5435:5432"

  wishlist-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=wishlist_db
      - POSTGRES_USER=wishlist
      - POSTGRES_PASSWORD=password
    networks:
      - app-network
    ports:
      - "5436:5432"

networks:
  app-network:
    driver: bridge
